openapi: 3.0.0
info:
  title: Payments App API
  description: API for Payment Gateways (Xendit, Midtrans, etc) wrapper.
  version: 1.0.0
servers:
  - url: http://site1.localhost:8000/api/method
    description: Local Development Server

paths:
  /payments.utils.create_payment_request:
    post:
      summary: Create Generic Payment Request
      description: Create a Payment Request record which triggers gateway processing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dt:
                  type: string
                  description: Document Type (e.g. Sales Order)
                dn:
                  type: string
                  description: Document Name
                payment_gateway_account:
                  type: string
                payer_email:
                  type: string
      responses:
        "200":
          description: Payment Request URL or Status

  /payments.templates.pages.payment_gateway.get_payment_url:
    get:
      summary: Get Payment Page URL
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Redirect URL
